### ISSUE TITLE
Docker demo warning. RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=35371] throws

### ISSUE THREAD

**Issue by alberttwong** [onetable-io/onetable#316]
```
presto          | 2024-02-03T14:17:07.494Z	WARN	RMI TCP Accept-0	sun.rmi.transport.tcp	RMI TCP Accept-0: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=35371] throws
presto          | java.net.SocketTimeoutException: Accept timed out
presto          | 	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
presto          | 	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
presto          | 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
presto          | 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
presto          | 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
presto          | 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
presto          | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by yegangy0718** [comment]
I got the exception as well when running demo 
```
presto          | 2024-03-19T18:37:42.535Z	WARN	RMI TCP Accept-37929	sun.rmi.transport.tcp	RMI TCP Accept-37929: accept loop for ServerSocket[addr=0.0.0.0/0.0.0.0,localport=37929] throws
presto          | java.net.SocketTimeoutException: Accept timed out
presto          | 	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
presto          | 	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
presto          | 	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
presto          | 	at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
presto          | 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.executeAcceptLoop(TCPTransport.java:394)
presto          | 	at java.rmi/sun.rmi.transport.tcp.TCPTransport$AcceptLoop.run(TCPTransport.java:366)
presto          | 	at java.base/java.lang.Thread.run(Thread.java:829)
```
Additionally, I don't find the line 
```
look for a log line during startup that contains `To access the server, open this file in a browser: ... 
```
Is it caused by the exception above?

**Comment by alberttwong** [comment]
it's a warning but doesn't stop the demo.
