### ISSUE TITLE
error in Jupyter notebook in docker demo

### ISSUE THREAD

**Issue by alberttwong** [onetable-io/onetable#317]
```
cell5.sc:10: value builder is not a member of object io.onetable.client.PerTableConfig
val perTableConfig = PerTableConfig.builder()
                                    ^
Compilation Failed
```

**Comment by alberttwong** [comment]
so if I fix it with `val perTableConfig = PerTableConfigImpl.builder()`.  I get this next error.

```
15:26:32.850 [scala-interpreter-1] ERROR io.onetable.spi.sync.TableFormatSync - Failed to sync snapshot
org.apache.iceberg.exceptions.ValidationException: Invalid Hive object for demo.hudi_dimCustomer
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:264) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.BaseMetastoreTableOperations.commit(BaseMetastoreTableOperations.java:135) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.BaseMetastoreCatalog$BaseMetastoreCatalogTableBuilder.create(BaseMetastoreCatalog.java:199) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.catalog.Catalog.createTable(Catalog.java:75) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at io.onetable.iceberg.IcebergTableManager.lambda$getOrCreateTable$4(IcebergTableManager.java:81) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_382]
	at io.onetable.iceberg.IcebergTableManager.getOrCreateTable(IcebergTableManager.java:79) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.iceberg.IcebergClient.initializeTableIfRequired(IcebergClient.java:155) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.iceberg.IcebergClient.beginSync(IcebergClient.java:147) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.spi.sync.TableFormatSync.getSyncResult(TableFormatSync.java:154) ~[onetable-api-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.spi.sync.TableFormatSync.syncSnapshot(TableFormatSync.java:70) ~[onetable-api-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.client.OneTableClient.syncSnapshot(OneTableClient.java:179) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at io.onetable.client.OneTableClient.sync(OneTableClient.java:116) ~[onetable-core-0.1.0-SNAPSHOT.jar:?]
	at ammonite.$sess.cell7$Helper.<init>(cell7.sc:21) ~[?:?]
	at ammonite.$sess.cell7$.<init>(cell7.sc:7) ~[?:?]
	at ammonite.$sess.cell7$.<clinit>(cell7.sc) ~[?:?]
	at ammonite.$sess.cell7.$main(cell7.sc) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$evalMain$1(Evaluator.scala:108) ~[?:?]
	at ammonite.util.Util$.withContextClassloader(Util.scala:24) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.runtime.Evaluator$$anon$1.evalMain(Evaluator.scala:90) ~[?:?]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$2(Evaluator.scala:127) ~[?:?]
	at ammonite.util.Catching.map(Res.scala:117) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.runtime.Evaluator$$anon$1.$anonfun$processLine$1(Evaluator.scala:121) ~[?:?]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.runtime.Evaluator$$anon$1.processLine(Evaluator.scala:120) ~[?:?]
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$5(Interpreter.scala:302) ~[?:?]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.interp.Interpreter.$anonfun$evaluateLine$2(Interpreter.scala:285) ~[?:?]
	at ammonite.util.Catching.flatMap(Res.scala:115) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.interp.Interpreter.evaluateLine(Interpreter.scala:284) ~[?:?]
	at ammonite.interp.Interpreter.$anonfun$processLine$6(Interpreter.scala:272) ~[?:?]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.interp.Interpreter.$anonfun$processLine$4(Interpreter.scala:255) ~[?:?]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.interp.Interpreter.$anonfun$processLine$2(Interpreter.scala:248) ~[?:?]
	at ammonite.util.Catching.flatMap(Res.scala:115) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at ammonite.interp.Interpreter.processLine(Interpreter.scala:247) ~[?:?]
	at almond.Execute.$anonfun$ammResult$7(Execute.scala:360) ~[?:?]
	at almond.internals.CaptureImpl.$anonfun$apply$2(CaptureImpl.scala:64) ~[?:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]
	at scala.Console$.withErr(Console.scala:196) ~[scala-library-2.12.18.jar:?]
	at almond.internals.CaptureImpl.$anonfun$apply$1(CaptureImpl.scala:56) ~[?:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]
	at scala.Console$.withOut(Console.scala:167) ~[scala-library-2.12.18.jar:?]
	at almond.internals.CaptureImpl.apply(CaptureImpl.scala:56) ~[?:?]
	at almond.Execute.capturingOutput(Execute.scala:246) ~[?:?]
	at almond.Execute.$anonfun$ammResult$6(Execute.scala:351) ~[?:?]
	at almond.Execute.$anonfun$withClientStdin$1(Execute.scala:225) ~[?:?]
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]
	at scala.Console$.withIn(Console.scala:230) ~[scala-library-2.12.18.jar:?]
	at almond.Execute.withClientStdin(Execute.scala:221) ~[?:?]
	at almond.Execute.$anonfun$ammResult$5(Execute.scala:351) ~[?:?]
	at almond.Execute.withInputManager(Execute.scala:211) ~[?:?]
	at almond.Execute.$anonfun$ammResult$4(Execute.scala:350) ~[?:?]
	at ammonite.repl.Signaller.apply(Signaller.scala:28) ~[?:?]
	at almond.Execute.interruptible(Execute.scala:275) ~[?:?]
	at almond.Execute.$anonfun$ammResult$3(Execute.scala:349) ~[?:?]
	at ammonite.util.Res$Success.flatMap(Res.scala:62) ~[ammonite-util_2.12-3.0.0-M0-56-1bcbe7f6.jar:3.0.0-M0-56-1bcbe7f6]
	at almond.Execute.$anonfun$ammResult$1(Execute.scala:336) ~[?:?]
	at almond.Execute.withOutputHandler(Execute.scala:237) ~[?:?]
	at almond.Execute.ammResult(Execute.scala:327) ~[?:?]
	at almond.Execute.apply(Execute.scala:535) ~[?:?]
	at almond.ScalaInterpreter.execute(ScalaInterpreter.scala:178) ~[?:?]
	at almond.interpreter.InterpreterToIOInterpreter.$anonfun$execute$2(InterpreterToIOInterpreter.scala:66) ~[?:?]
	at cats.effect.IOFiber.runLoop(IOFiber.scala:255) ~[?:?]
	at cats.effect.IOFiber.autoCedeR(IOFiber.scala:1421) ~[?:?]
	at cats.effect.IOFiber.run(IOFiber.scala:119) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_382]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_382]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_382]
Caused by: org.apache.hadoop.hive.metastore.api.InvalidObjectException: database hive.demo
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42216) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result$create_table_with_environment_context_resultStandardScheme.read(ThriftHiveMetastore.java:42193) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$create_table_with_environment_context_result.read(ThriftHiveMetastore.java:42119) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:88) ~[libthrift-0.12.0.jar:0.12.0]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_create_table_with_environment_context(ThriftHiveMetastore.java:1203) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.create_table_with_environment_context(ThriftHiveMetastore.java:1189) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.create_table_with_environment_context(HiveMetaStoreClient.java:2396) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:750) ~[hive-metastore-2.3.9.jar:2.3.9]
	at org.apache.hadoop.hive.metastore.HiveMetaStoreClient.createTable(HiveMetaStoreClient.java:738) ~[hive-metastore-2.3.9.jar:2.3.9]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_382]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_382]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_382]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_382]
	at org.apache.hadoop.hive.metastore.RetryingMetaStoreClient.invoke(RetryingMetaStoreClient.java:169) ~[hive-metastore-2.3.9.jar:2.3.9]
	at com.sun.proxy.$Proxy17.createTable(Unknown Source) ~[?:?]
	at org.apache.iceberg.hive.HiveTableOperations.lambda$persistTable$3(HiveTableOperations.java:345) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:58) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.ClientPoolImpl.run(ClientPoolImpl.java:51) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.hive.CachedClientPool.run(CachedClientPool.java:122) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.hive.HiveTableOperations.persistTable(HiveTableOperations.java:343) ~[iceberg-hive-runtime-1.3.1.jar:?]
	at org.apache.iceberg.hive.HiveTableOperations.doCommit(HiveTableOperations.java:247) ~[iceberg-hive-runtime-1.3.1.jar:?]
	... 73 more
15:26:32.871 [scala-interpreter-1] ERROR io.onetable.client.OneTableClient - Sync failed for the following formats ICEBERG
```

**Comment by alberttwong** [comment]
Had to execute `create schema hive.demo` in the trino container.

**Comment by the-other-tim-brown** [comment]
Yes there is a line in the notebook about the hive catalog.
